language: java
jdk:
- oraclejdk8
script: mvn -f parent/pom.xml deploy
after_success:
- git clone --depth=1 -b gh-pages https://${GH_TOKEN}@github.com/PizzaFactory/cli-parser.git gh-pages
- cd gh-pages
- mvn process-resources install
env:
  global:
  - MAVEN_OPTS=-Xmx1024m
  - PIZZAFACTORY_VERSION=8.5
  - GIT_COMMITTER_NAME="Masaki Muranaka"
  - GIT_COMMITTER_EMAIL="monaka@monami-ya.jp"
  - secure: "htmt0vRHpzOSY0eGEZC7qzo9C9OcalnNkpPD1EXHK+1mJgofhBAnIQklv0PnmuIsCsdE5kEmmH0qIxJvc3q3Ubz6SWbb3lMhizifmoeOZY3MOfDzTssjTpgSmcszbXSCA+n8QL/Da2gx3rET98GEuIsnTfWtTSn5hRvvs767k8GCKYp6Eu6hMrsu8P6GLZ7Lym/46nCV5VCLP7LNunWWagxw40vwrsDM0Dhmm6TFvsQZSJ6jjHK49NJQ9IsRtl1rDoo7w4B4IbI9C9I44N8cr66UIfj9/vwNlXw7cn9NgwurdhlcZojmTThK9K45JBpEX0kqlYiFBWrNSwkqiijW/7k9M8SISMkOgMwzyZ1b0hTb7CXuKXaAR6QfAH60o/pAoaFMOjRDGk1a4StousyTIyKuwmEw7b6OyMPQ2oFTXi7TDv9iSljQDsmfd1aGwogI+dK6tiW5yei80k94J/ZDDhTxrgv68JMQpbPjVYhlhchK1TJ8LGZe4K1OFJfEc/s4zDblv3fRFC5ZfRVKj0QJwGe/IGYuoes440UcB7Z8EIHw/KaVrHCTVu/D0W60UShjyWFDyxbsVVz7RZUCuwGdRLRRcMuDIQPEKjCXmijef8tZj544S2aTGRQA7Re4szu1oB/sKGHEhhSxXc6uNKlSofYOkSHgY/zbKyZS8UDwYKc="
